/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klockiIPojemniki;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;

/**
 *
 * @author Marysia
 */
public class KlockiIPojemniki extends javax.swing.JFrame {

    /**
     * Creates new form KlockiIPojemniki
     */
    public KlockiIPojemniki() {
        initComponents();
    }
    
    Action Zapakuj=new AbstractAction("Zapakuj"){
        @Override
                public void actionPerformed(ActionEvent e){
                    zapakuj();
                }
    };

    public void zapakuj() {
        double iloscKlockowDoSpakowania =  Double.parseDouble(jTextFieldIloscKlockowDoSpakowania.getText());
        double iloscKlockowWPojemniku = Double.parseDouble(jTextFieldloscKlockowWPojemniku.getText());
        
        double iloscPudelek;
        double iloscKlockowWOstatnimPudelku = 0;
             iloscPudelek =Math.ceil(iloscKlockowDoSpakowania / iloscKlockowWPojemniku );
        if(iloscKlockowDoSpakowania > iloscKlockowWPojemniku){
            
            iloscKlockowWOstatnimPudelku = iloscKlockowDoSpakowania % iloscKlockowWPojemniku;
        }
        
        jTextFieldIloscZapakowanychPudelek.setText(Double.toString(iloscPudelek));
        jTextFieldIloscWOstatnimPudelku.setText(Double.toString(iloscKlockowWOstatnimPudelku > 0 ? iloscKlockowWOstatnimPudelku : 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIloscKlockowWPojemniku = new javax.swing.JLabel();
        jLabelIloscKlockowDoSpakowania = new javax.swing.JLabel();
        jTextFieldloscKlockowWPojemniku = new javax.swing.JTextField();
        jTextFieldIloscKlockowDoSpakowania = new javax.swing.JTextField();
        javax.swing.JButton jButtonZapakuj = new javax.swing.JButton();
        jLabelIloscZapakowanychPudelek = new javax.swing.JLabel();
        jLabelIloscWOstatnimPudelku = new javax.swing.JLabel();
        jTextFieldIloscZapakowanychPudelek = new javax.swing.JTextField();
        jTextFieldIloscWOstatnimPudelku = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelIloscKlockowWPojemniku.setText("Ile klocków mieści się w pojemniku");

        jLabelIloscKlockowDoSpakowania.setText("Ile klocków spakować");

        jTextFieldloscKlockowWPojemniku.setToolTipText("");

        jTextFieldIloscKlockowDoSpakowania.setToolTipText("");

        jButtonZapakuj.setAction(Zapakuj);
        jButtonZapakuj.setText("Zapakuj");

        jLabelIloscZapakowanychPudelek.setText("Zapakowano w");

        jLabelIloscWOstatnimPudelku.setText("W ostatnim pudełku jest");

        jTextFieldIloscZapakowanychPudelek.setEditable(false);

        jTextFieldIloscWOstatnimPudelku.setEditable(false);

        jLabel1.setText("pudełka");

        jLabel2.setText("klockoów");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIloscZapakowanychPudelek)
                    .addComponent(jLabelIloscWOstatnimPudelku)
                    .addComponent(jLabelIloscKlockowDoSpakowania)
                    .addComponent(jLabelIloscKlockowWPojemniku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldloscKlockowWPojemniku, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIloscKlockowDoSpakowania, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldIloscWOstatnimPudelku, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIloscZapakowanychPudelek, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonZapakuj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIloscKlockowWPojemniku)
                    .addComponent(jTextFieldloscKlockowWPojemniku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIloscKlockowDoSpakowania)
                    .addComponent(jTextFieldIloscKlockowDoSpakowania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonZapakuj)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIloscZapakowanychPudelek)
                    .addComponent(jTextFieldIloscZapakowanychPudelek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIloscWOstatnimPudelku)
                    .addComponent(jTextFieldIloscWOstatnimPudelku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlockiIPojemniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlockiIPojemniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlockiIPojemniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlockiIPojemniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlockiIPojemniki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelIloscKlockowDoSpakowania;
    private javax.swing.JLabel jLabelIloscKlockowWPojemniku;
    private javax.swing.JLabel jLabelIloscWOstatnimPudelku;
    private javax.swing.JLabel jLabelIloscZapakowanychPudelek;
    private javax.swing.JTextField jTextFieldIloscKlockowDoSpakowania;
    private javax.swing.JTextField jTextFieldIloscWOstatnimPudelku;
    private javax.swing.JTextField jTextFieldIloscZapakowanychPudelek;
    private javax.swing.JTextField jTextFieldloscKlockowWPojemniku;
    // End of variables declaration//GEN-END:variables
}
